//! Rust↔Python feature parity: verifies `token_keys` / `bucket_tokens`
//! against `fixtures/hash_vectors.json`, generated by the independent Python
//! implementation (`train/spellman_features.py`, `uv run spellman-gen-fixtures`).
//!
//! Both implementations are written from the same spec; the fixture is the
//! arbiter. If this test fails after a change on either side, the two sides
//! have drifted and every trained model is invalid.

use std::fs;
use std::path::Path;

use spellman_detector::features::{bucket_tokens, token_keys, FeatureConfig};
use spellman_detector::hash::{FeatureHasher, HashId};
use serde::Deserialize;

#[derive(Deserialize)]
struct Case {
    text: String,
    hash_id: String,
    seed: u32,
    n_min: u8,
    n_max: u8,
    log2_d: u32,
    keys: Vec<String>,
    buckets: Vec<u32>,
    negs: Vec<u8>,
}

#[derive(Deserialize)]
struct Fixture {
    cases: Vec<Case>,
}

#[test]
fn rust_matches_python_fixture() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures/hash_vectors.json");
    let fixture: Fixture = serde_json::from_str(&fs::read_to_string(&path).unwrap())
        .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));

    assert!(!fixture.cases.is_empty(), "empty fixture — run `uv run spellman-gen-fixtures` in train/");
    for case in &fixture.cases {
        let cfg = FeatureConfig { n_min: case.n_min, n_max: case.n_max };
        let hasher = FeatureHasher {
            id: HashId::from_id(&case.hash_id).unwrap_or_else(|| panic!("unknown hash id {}", case.hash_id)),
            seed: case.seed,
        };

        let keys: Vec<String> = token_keys(&case.text, &cfg)
            .into_iter()
            .map(|k| k.to_string())
            .collect();
        let expected_keys: Vec<String> = case.keys.clone();
        assert_eq!(
            keys, expected_keys,
            "token keys diverge for {:?} ({})",
            case.text.chars().take(30).collect::<String>(),
            case.hash_id
        );

        let toks = bucket_tokens(&case.text, &cfg, &hasher, case.log2_d);
        let buckets: Vec<u32> = toks.iter().map(|t| t.bucket).collect();
        let negs: Vec<u8> = toks.iter().map(|t| t.neg as u8).collect();
        assert_eq!(
            buckets, case.buckets,
            "buckets diverge for {:?} ({}, log2_d={})",
            case.text.chars().take(30).collect::<String>(),
            case.hash_id,
            case.log2_d
        );
        assert_eq!(negs, case.negs, "sign bits diverge for {}", case.hash_id);
    }
}
